services:
  track:
    container_name: track-service
    build:
      context: .
      dockerfile: ./track-service/Dockerfile
    ports:
      - "${TRACK_SERVICE_PORT}:${TRACK_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./migrations:/app/migrations

  db:
    image: postgres:16
    container_name: retry-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  migrate:
    image: migrate/migrate:v4.17.0
    volumes:
      - ./migrations:/work/migrations
    command:
      - "-path=/work/migrations"
      - "-database=${DATABASE_URL}"
      - "up"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: track-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - track
    restart: unless-stopped

volumes:
  pg_data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450