version: "3.9"

services:
  track:
    container_name: track-service
    build:
      context: .
      dockerfile: ./track-service/Dockerfile
    ports:
      - "${TRACK_SERVICE_PORT}:${TRACK_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./migrations:/app/migrations  # чтобы track видел миграции (если надо)

  db:
    image: postgres:16
    container_name: retry-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=${DATABASE_URL}"
      - "up"
    depends_on:
      - db

volumes:
  pg_data: