basePath: /
definitions:
  domain.Action:
    properties:
      actionTypeID:
        type: integer
      id:
        format: int64
        type: integer
      ipaddress:
        type: string
      source:
        type: string
      timestamp:
        type: string
      visitID:
        type: string
    type: object
  github_com_Vovarama1992_retry_track-service_internal_visit_models.VisitSourceStat:
    properties:
      count:
        type: integer
      source:
        type: string
    type: object
  internal_visit_delivery.VisitRequestDTO:
    properties:
      source:
        type: string
      timestamp:
        type: string
      visit_id:
        type: string
    required:
    - source
    - timestamp
    - visit_id
    type: object
info:
  contact: {}
  description: Сервис для отслеживания визитов и действий
  title: Track Service API
  version: "1.0"
paths:
  /track/stats/by-source:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_Vovarama1992_retry_track-service_internal_visit_models.VisitSourceStat'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Статистика по источникам визитов
  /track/visit:
    post:
      consumes:
      - application/json
      description: Создаёт новое действие типа "visit"
      parameters:
      - description: Информация о визите
        in: body
        name: visit
        required: true
        schema:
          $ref: '#/definitions/internal_visit_delivery.VisitRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Зафиксировать визит
  /track/visit/all:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Action'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить все визиты
swagger: "2.0"
