basePath: /
definitions:
  domain.Action:
    properties:
      actionTypeID:
        type: integer
      actionTypeName:
        description: опционально, может быть пустым
        type: string
      id:
        format: int64
        type: integer
      ipaddress:
        type: string
      meta:
        description: хранит meta как JSON, можно парсить в map при необходимости
        items:
          type: integer
        type: array
      sessionID:
        type: string
      source:
        type: string
      timestamp:
        type: string
      visitID:
        type: string
    type: object
  domain.SessionStats:
    properties:
      avg_actions_per_session:
        type: number
      avg_duration_seconds:
        type: number
      first_session_at:
        type: string
      last_session_at:
        type: string
      max_actions_per_session:
        type: integer
      max_duration_seconds:
        type: number
      total_actions:
        type: integer
      total_sessions:
        type: integer
    type: object
  github_com_Vovarama1992_retry_track-service_internal_domain.VisitBlock:
    properties:
      sessions:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
    type: object
  github_com_Vovarama1992_retry_track-service_internal_visit_models.VisitSourceStat:
    properties:
      count:
        type: integer
      source:
        type: string
    type: object
  internal_delivery.ActionRequestDTO:
    properties:
      meta:
        items:
          type: integer
        type: array
      session_id:
        type: string
      source:
        type: string
      timestamp:
        type: string
      type:
        type: string
      visit_id:
        type: string
    required:
    - session_id
    - source
    - timestamp
    - type
    - visit_id
    type: object
  internal_visit_delivery.VisitRequestDTO:
    properties:
      session_id:
        type: string
      source:
        type: string
      timestamp:
        type: string
      visit_id:
        type: string
    required:
    - session_id
    - source
    - timestamp
    - visit_id
    type: object
info:
  contact: {}
  description: Сервис для отслеживания визитов, сессий и действий
  title: Track Service API
  version: "1.0"
paths:
  /track/action:
    post:
      consumes:
      - application/json
      parameters:
      - description: Информация о действии
        in: body
        name: action
        required: true
        schema:
          $ref: '#/definitions/internal_delivery.ActionRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Зафиксировать действие
      tags:
      - Actions
  /track/action/all:
    get:
      parameters:
      - description: Смещение выборки (offset)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Action'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить все действия
      tags:
      - Actions
  /track/action/grouped:
    get:
      parameters:
      - description: Смещение выборки (offset)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/domain.Action'
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить действия, сгруппированные по visit_id
      tags:
      - Actions
  /track/action/grouped-by-session:
    get:
      parameters:
      - description: Смещение выборки (offset)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/domain.Action'
              type: array
            type: object
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить действия, сгруппированные по session_id
      tags:
      - Sessions
  /track/session/grouped-by-visit:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить количество сессий на каждый visit_id
      tags:
      - Sessions
  /track/session/stats:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SessionStats'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить статистику по сессиям
      tags:
      - Sessions
  /track/stats/by-source:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_Vovarama1992_retry_track-service_internal_visit_models.VisitSourceStat'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Статистика по источникам визитов
      tags:
      - Visits
  /track/visit:
    post:
      consumes:
      - application/json
      description: Создаёт новое действие типа "visit"
      parameters:
      - description: Информация о визите
        in: body
        name: visit
        required: true
        schema:
          $ref: '#/definitions/internal_visit_delivery.VisitRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Зафиксировать визит
      tags:
      - Visits
  /track/visit/all:
    get:
      parameters:
      - description: Смещение выборки (offset)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Action'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить все визиты
      tags:
      - Visits
  /track/visits:
    get:
      parameters:
      - description: Смещение выборки (offset)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/github_com_Vovarama1992_retry_track-service_internal_domain.VisitBlock'
            type: object
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить читабельную сводку по визитам (сессии и события внутри)
      tags:
      - Sessions
swagger: "2.0"
